app/blueprints/generation/txt_gen/routes.py
# UDPDATE ME!
import json
import flask
import requests
import os

import urllib.request
import urllib.parse
import urllib.error

from flask import redirect, request, render_template, url_for, Blueprint, send_from_directory, current_app, session
from flask_login import login_required
from app.app import db

from app.models import Generation

from app.blueprints.generation.helper import blueprint_add, generation_add, get_local_ip

txt_gen = Blueprint("txt_gen", __name__, template_folder='templates', static_folder='static')

# Need to import Blueprint after creating blueprint since that's the name of my model. Bad name need to fix later.
from app.models import Blueprint

@txt_gen.route('/')
@login_required
def index():
    if(not Blueprint.query.filter_by(id=1).first() or Blueprint.query.filter_by(id=1).first().title != 'txt_gen'):
        blueprint_add('txt_gen', 1)
    return render_template('txt_gen/index.html')

#this is to serve the javascript files to the browser in the html files
@txt_gen.route('/static/js/<path:filename>')
def serve_js(filename):
    # print("text", txt_gen.static_folder+'/js/'+filename)
    return send_from_directory(txt_gen.static_folder+'/js/', filename, mimetype='application/javascript')


# This is to view the image generated by ComfyUI. 
@txt_gen.route("/<endpoint>", methods=['GET'])
@login_required
def get_endpoint(endpoint=None):
    args = flask.request.args
    if len(args) > 0:
        queries = urllib.parse.urlencode(dict(args))
        try:
            res = urllib.request.urlopen(
                f"http://{get_local_ip()}:8188/{endpoint}?{queries}")
            print(res.url)
            generation_add(res.url, Blueprint.query.filter_by(id=1).first().id)
            # update_db(res.url)
            return res
        except urllib.error.HTTPError as e:
            return e.read()

    req = urllib.request.Request(
        f"http://{get_local_ip()}:8188/{endpoint}")
    try:
        response = urllib.request.urlopen(req)
        return response
    except urllib.error.HTTPError as e:
        return e.read()

# todo: 'add get and post to javascript or figure out how to make specfic routes '
# This is to generate the image by ComfyUI. Is this the only thing that generates and returns the image?
@txt_gen.route("/<endpoint>", methods=['POST'])
@login_required
def post_endpoint(endpoint=None):
    payload = flask.request.get_json()
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(
        f"http://{get_local_ip()}:8188/{endpoint}", data=data)
    try:
        response = urllib.request.urlopen(req)
        return response
    except urllib.error.HTTPError as e:
        return e.read()

app/blueprints/generation/templates/generation/index.html
{% extends "base.html" %}
{% block title %}Workflows{% endblock %}


{% block content %}
<div class="flex flex-col items-center">
    <h1 class="font-bold text-9xl mb-20 lg:text-5xl lg:mb-10">Workflows</h1>
    <div class="menu menu-vertical">
        <a href="{{ url_for('txt_gen.index') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Text Gen SD3</button></a>
        <a href="{{ url_for('fantasy_character_creator.index') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-60 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Fantasy Character Creator</button></a>
        <a href="{{ url_for('ip_adapter_headshot.index') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Dress U Up</button></a>
        <!-- EDIT10 -->
        <!-- Update my_new_workflow to match your workflow name. Update My New Workflow to match your workflow name, this is what is displayed on the button. remove the # below to remove the jinja comment -->
        <!-- <a href="{#{ url_for('my_new_workflow.index') }#}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">My New Workflow</button></a> -->
    </div>
</div>
{% endblock %}