app/blueprints/help/routes.py
from flask import render_template, Blueprint

#import model
from app.models import User

help = Blueprint("help", __name__, template_folder='templates')

@help.route('/')
def index():
    users = User.query.all()
    return render_template('help/index.html')

@help.route('/getting_started')
def getting_started():
    return render_template('help/getting_started.html')

@help.route('/txt_gen')
def txt_gen():
    return render_template('help/txt_gen.html')

@help.route('/fantasy_character_creator')
def fantasy_character_creator():
    return render_template('help/fantasy_character_creator.html')

@help.route('/ip_adapter_headshot')
def ip_adapter_headshot():
    return render_template('help/ip_adapter_headshot.html')

#EDIT12
# Rename to your workflow name and Uncomment the lines below.
# @help.route('/my_new_workflow')
# def my_new_workflow():
#     return render_template('help/my_new_workflow.html')

app/blueprints/help/templates/help/demo_workflow.html
{% extends "base.html" %}
{% block title %}Dress U Up - Help{% endblock %}
{% block content %}
<div class="flex">
    <div class="mx-auto">
        <h1 class="text-8xl lg:text-5xl font-bold mb-20 lg:mb-5 text-center">Dress U Up - Requirements</h1>
        <p class="mb-20 lg:mb-5 text-5xl lg:text-base">To be able to use the Dress U up, you need to download a custom node from the ComfyUI manager, download a couple models and place it in the apporpriate directory and install FaceID dependencies.</p>
        <div class="flex mb-5 w-full">
                <ol class="flex flex-col list-decimal list-inside text-3xl lg:text-base">
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Install ComfyUI-IPAdapter_plus from the ComfyUI manager. The ID is 98 and author is cubiq.</li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Follow the installation instructions from the 
                        <a class="link text-blue-500" href="https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file">
                            IPAdapter Plus
                        </a>
                        repo.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Follow the video instructions on installing 
                        <a class="link text-blue-500" href="https://www.youtube.com/watch?v=vCCVxGtCyho">
                            FaceID
                        </a>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">You probably have python 3.11.* installed - 
                        <a class="link text-blue-500" href="https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl">
                            download this whl
                        </a>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Run this command in cmd within your root ComfyUI directory:
                        <code class="bg-black text-white dark:text-black dark:bg-white">.\python_embeded\python.exe -m pip install "C:\Users\jorda\Downloads\insightface-0.7.3-cp311-cp311-win_amd64.whl" onnxruntime</code>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Search for #Edit1 then update the app.config. Replace jorda with your username and replace ComfyUI_windows_portable_3 with your ComfyUI directory name.</li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://civitai.com/api/download/models/272399">
                            realisticVisionV60B1_v60B1VAE.safetensors
                        </a>
                        and place it in ComfyUI_windows_portable\ComfyUI\models\checkpoints.
                    </li>
                </ol>
        </div>
    </div>
</div>
{% endblock %}

app/blueprints/help/templates/help/fantasy_character_creator.html
{% extends "base.html" %}
{% block title %}Fantasy Character Creator - Help{% endblock %}
{% block content %}
<div class="flex">
    <div class="mx-auto">
        <h1 class="text-8xl lg:text-5xl font-bold mb-20 lg:mb-5 text-center">Fantasy Character Creator - Requirements</h1>
        <p class="mb-20 lg:mb-5 text-5xl lg:text-base"> To be able to use the Fantasy Character Creator, you need to download a custom node from the ComfyUI manager, download a couple models and place it in the apporpriate directory.</p>
        
        <!-- Video Section -->
        <div class="mb-4">
            <h2 class="text-2xl lg:text-xl font-bold mb-4 text-center">Video Tutorial</h2>
            <div class="video-container w-full aspect-w-16 aspect-h-9">
                <!-- Replace with your video embed code (YouTube, Vimeo, etc.) -->
                <iframe height="720" class="w-full" src="https://www.youtube.com/embed/VWKiN88gRsU?si=Md1p5VKnepm7HtyY" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
        
        <div class="text-2xl lg:text-xl font-bold mb-4 text-center">Text Instructions</div>
        <div class="flex mb-5 w-full">
                <ol class="flex flex-col list-decimal list-inside text-3xl lg:text-base">
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Install ComfyUI Essentials from the ComfyUI manager. The ID is 233 and author is cubiq.</li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download
                        <a class="link text-blue-500" href="https://huggingface.co/dataautogpt3/ProteusV0.3/resolve/main/ProteusV0.3.safetensors?download=true">
                            Proteus V0.3
                        </a>
                        and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\checkpoints.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download
                        <a class="link text-blue-500" href="https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_v2_1.safetensors?download=true">
                            DreamShaperTurbo v2.x
                        </a>
                        and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\checkpoints.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download
                        <a class="link text-blue-500" href="https://huggingface.co/latent-consistency/lcm-lora-sdxl/resolve/main/pytorch_lora_weights.safetensors?download=true">
                            SDXL LCM Lora
                        </a>
                        then rename to <code class="bg-black text-white dark:text-black dark:bg-white">lcm-lora-sdxl.safetensors</code> and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\loras.
                    </li>
                </ol>
        </div>
    </div>
</div>
{% endblock %}

app/blueprints/help/templates/help/getting_started.html
{% extends "base.html" %}
{% block title %}Getting Started{% endblock %}

{% block content %}
<div class="flex flex-col items-center px-4">
    <div class="w-full max-w-5xl">
        <h1 class="text-4xl lg:text-5xl font-bold mb-10 lg:mb-5 text-center">Getting Started</h1>
        <p class="mb-10 lg:mb-5 text-xl lg:text-base text-center">I'll walk you through how to code your own workflow page in Comfy Image Workshop. Watch the video below or follow the text instructions.</p>
        
        <!-- Video Section -->
        <div class="mb-4">
            <h2 class="text-2xl lg:text-xl font-bold mb-4 text-center">Video Tutorial</h2>
            <div class="video-container w-full aspect-w-16 aspect-h-9">
                <!-- Replace with your video embed code (YouTube, Vimeo, etc.) -->
                <iframe height="580" class="w-full" src="https://www.youtube.com/embed/na168v7YQOY?si=4P9bnktFJef_JvRN" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>

        <div class="text-2xl lg:text-xl font-bold mb-4 text-center">Text Instructions</div>
        <ol class="flex flex-col list-decimal list-inside text-lg lg:text-base space-y-6">
            <li>Go to this CIW directory Comfy_Image_Workshop\app\blueprints\generation</li>
            <li>Make a copy the demo_workflow directory in the same directory and give it a name appropriate to the workflow you are creating. For the sake of this example I will use my_new_workflow</li>
            <li>Open \my_new_workflow\templates and rename the \demo_workflow with \my_new_workflow.</li>
            <li>Now go to \Comfy_Image_Workshop\app\blueprints\help\templates\help and make a copy of the demo_workflow.html file and rename it to my_new_workflow. This is where you will be listing all the dependencies for your workflow.</li>
            <li>Now go to \Comfy_Image_Workshop\app\ and open app.py</li>
            <li>Search for #EDIT1 then update the app.config. Replace jorda with your username</li>
            <li>Search for #EDIT2 then look for the commented out import sample workflow then rename it to my_new_workflow</li>
            <li>Search for #EDIT3 then look for the commented out register sample workflow then rename it to my_new_workflow</li>
            <li>Now go to \Comfy_Image_Workshop\blueprints\generation\my_new_workflow\ and open routes.py</li>
            <li>Search for #EDIT4 then follow the instructions.</li>
            <li>Search for #EDIT5 then follow the instructions. ID must be unique.</li>
            <li>Search for #EDIT6 then follow the instructions. ID must match #EDIT5 ID.</li>
            <li>Now head to ComfyUI <a href="http://127.0.0.1:8188" target="_blank" class="link text-blue-500">127.0.0.1:8188</a> and design your workflow.</li>
            <li>Be sure to record any of the custom nodes you downloaded or the models you used in your workflow. Ex: checkpoint files, loras, controlnets, etc.. You will need to list them in the help file you created earlier.</li>
            <li>Click on the cog icon above Queue Prompt and look for Enable Dev mode Options and enable it. This will allow you to download the JSON format of the workflow.</li>
            <li>Once you have completed your workflow, click on save (API Format). Rename your workflow to something appropriate. For the sake of this example lets rename to json_workflow</li>
            <li>Now go to \Comfy_Image_Workshop\blueprints\generation\my_new_workflow\static\js and move your json_workflow in this directory.</li>
            <li>Now go to \Comfy_Image_Workshop\blueprints\generation\my_new_workflow\static\js Now open app.js</li>
            <li>Search for EDIT7 and follow the instructions.</li>
            <li>Search for EDIT8 and follow the instructions. This is optional, depending on your workflow.</li>
            <li>Now go to \Comfy_Image_Workshop\app\blueprints\generation\my_new_workflow\templates\my_new_workflow and open index.html</li>
            <li>Search for EDIT9 and replace my_new_workflow with the name of your workflow.</li>
            <li>Now review the code in \Comfy_Image_Workshop\app\blueprints\generation\my_new_workflow\templates\my_new_workflow\index.html</li>
            <li>Now review the code in \Comfy_Image_Workshop\app\blueprints\generation\my_new_workflow\static\js\app.js</li>
            <li>Once you reviewed index.html and app.js and understand it, Now you can update the code to match your workflow to get it to run.</li>
            <li>Once you have completed your workflow, now go to \Comfy_Image_Workshop\app\blueprints\generation\templates\generation and open index.html</li>
            <li>Search for EDIT10 and follow the instructions.</li>
            <li>Now go to \Comfy_Image_Workshop\app\help\templates\help and open index.html</li>
            <li>Search for EDIT11 and follow the instructions.</li>
            <li>Now go to \Comfy_Image_Workshop\app\help and open routes.py</li>
            <li>Search for EDIT12 and follow the instructions.</li>
            <li>Now go to \Comfy_Image_Workshop\app\help\templates\help and open my_new_workflow.html</li>
            <li>Edit the instructions on how to install dependencies to use your workflow.</li>
            <li>Great job 👏 Now you have completed your workflow and you can push it to the GitHub repo to share your workflow with the community.</li>
        </ol>
    </div>
</div>
{% endblock %}

app/blueprints/help/templates/help/index.html
{% extends "base.html" %}
{% block title %}Help{% endblock %}


{% block content %}
<div class="flex flex-col items-center">
    <h1 class="font-bold text-9xl mb-20 lg:text-5xl lg:mb-10">Help</h1>
    <div class="menu menu-vertical">
        <a href="{{ url_for('help.getting_started') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Getting Started</S></button></a>
        <a href="{{ url_for('help.txt_gen') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Text Gen SD3</button></a>
        <a href="{{ url_for('help.fantasy_character_creator') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-60 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Fantasy Character Creator</button></a>
        <a href="{{ url_for('help.ip_adapter_headshot') }}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">Dress U Up</button></a>
        <!-- EDIT11 -->
        <!-- Update my_new_workflow to match your workflow name. Update My New Workflow to match your workflow name, this is what is displayed on the button. remove the # below to remove the jinja comment -->
        <!-- <a href="{#{ url_for('help.my_new_workflow') }#}"><button class="btn btn-primary bg-primary rounded-lg w-full pt-8 pb-32 lg:pb-16 mb-20 lg:mb-5 text-8xl lg:text-4xl" type="button">My New Workflow</button></a> -->
    </div>
</div>
{% endblock %}

app/blueprints/help/templates/help/ip_adapter_headshot.html
{% extends "base.html" %}
{% block title %}Dress U Up - Help{% endblock %}
{% block content %}
<div class="flex">
    <div class="mx-auto">
        <h1 class="text-8xl lg:text-5xl font-bold mb-20 lg:mb-5 text-center">Dress U Up - Requirements</h1>
        <p class="mb-20 lg:mb-5 text-5xl lg:text-base">To be able to use the Dress U up, you need to download a custom node from the ComfyUI manager, download a couple models and place it in the apporpriate directory and install FaceID dependencies.</p>
        
        <!-- Video Section -->
        <div class="mb-4">
            <h2 class="text-2xl lg:text-xl font-bold mb-4 text-center">Video Tutorial</h2>
            <div class="video-container w-full">
                <!-- Replace with your video embed code (YouTube, Vimeo, etc.) -->
                <iframe height="720" width="1280" class="" src="https://www.youtube.com/embed/6AgqzJ9ChA8?si=CGa5XrVAprDBtzFG" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>

        <div class="text-2xl lg:text-xl font-bold mb-4 text-center">Text Instructions</div>
        <div class="flex mb-5 w-full">
                <ol class="flex flex-col list-decimal list-inside text-3xl lg:text-base">
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Install ComfyUI-IPAdapter_plus from the ComfyUI manager. The ID is 98 and author is cubiq.</li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://civitai.com/models/4201?modelVersionId=245598">
                            realisticVisionV60B1_v60B1VAE.safetensors
                        </a>
                        and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\checkpoints.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors">
                            CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
                        </a>
                        download and rename to CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors then place in ComfyUI_windows_portable_CIW\ComfyUI\models\clip_vision.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors">
                            CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors
                        </a>
                        download and rename to CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors then place in ComfyUI_windows_portable_CIW\ComfyUI\models\clip_vision.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-full-face_sd15.safetensors">
                            ip-adapter-full-face_sd15.safetensors
                        </a>
                        and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\ipadapter.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sd15.bin">
                            ip-adapter-faceid-plusv2_sd15.bin
                        </a>
                        and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\ipadapter.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sd15_lora.safetensors">
                            Ip-adapter-faceid-plusv2_sd15_lora.safetensors
                        </a>
                        and place it in ComfyUI_windows_portable_CIW\ComfyUI\models\loras.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Follow the video instructions on installing 
                        <a class="link text-blue-500" href="https://www.youtube.com/watch?v=vCCVxGtCyho">
                            FaceID
                        </a>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Skip step 3 if you have python 3.11.* installed - 
                        <a class="link text-blue-500" href="https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl">
                            download this whl
                        </a>
                        and keep in downloads folder.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Change jorda to your username. Then run this command in cmd within your root ComfyUI directory:
                        <p><code class="bg-black text-white dark:text-black dark:bg-white">.\python_embeded\python.exe -m pip install "C:\Users\jorda\Downloads\insightface-0.7.3-cp311-cp311-win_amd64.whl" onnxruntime</code></p>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Search for #Edit1 in app\app.py then update the app.config. Replace jorda with your username.</li>
                </ol>
        </div>
    </div>
</div>
{% endblock %}

app/blueprints/help/templates/help/template_workflow.html
{% extends "base.html" %}
{% block title %}Dress U Up - Help{% endblock %}
{% block content %}
<div class="flex">
    <div class="mx-auto">
        <h1 class="text-8xl lg:text-5xl font-bold mb-20 lg:mb-5 text-center">Dress U Up - Requirements</h1>
        <p class="mb-20 lg:mb-5 text-5xl lg:text-base">To be able to use the Dress U up, you need to download a custom node from the ComfyUI manager, download a couple models and place it in the apporpriate directory and install FaceID dependencies.</p>
        <div class="flex mb-5 w-full">
                <ol class="flex flex-col list-decimal list-inside text-3xl lg:text-base">
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Install ComfyUI-IPAdapter_plus from the ComfyUI manager. The ID is 98 and author is cubiq.</li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Follow the installation instructions from the 
                        <a class="link text-blue-500" href="https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file">
                            IPAdapter Plus
                        </a>
                        repo.
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Follow the video instructions on installing 
                        <a class="link text-blue-500" href="https://www.youtube.com/watch?v=vCCVxGtCyho">
                            FaceID
                        </a>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">You probably have python 3.11.* installed - 
                        <a class="link text-blue-500" href="https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl">
                            download this whl
                        </a>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Run this command in cmd within your root ComfyUI directory:
                        <code class="bg-black text-white dark:text-black dark:bg-white">.\python_embeded\python.exe -m pip install "C:\Users\jorda\Downloads\insightface-0.7.3-cp311-cp311-win_amd64.whl" onnxruntime</code>
                    </li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Search for #Edit1 then update the app.config. Replace jorda with your username and replace ComfyUI_windows_portable_3 with your ComfyUI directory name.</li>
                    <li class="text-4xl lg:text-base mb-20 lg:mb-3">Download the model
                        <a class="link text-blue-500" href="https://civitai.com/api/download/models/272399">
                            realisticVisionV60B1_v60B1VAE.safetensors
                        </a>
                        and place it in ComfyUI_windows_portable\ComfyUI\models\checkpoints.
                    </li>
                </ol>
        </div>
    </div>
</div>
{% endblock %}

app/blueprints/help/templates/help/txt_gen.html
{% extends "base.html" %}
{% block title %}Text Gen SD3 - Help{% endblock %}
{% block content %}
<div class="flex">
    <div class="mx-auto">
        <h1 class="text-8xl lg:text-5xl font-bold mb-20 lg:mb-5 text-center">Text Gen SD3 - Requirements</h1>
        <p class="mb-20 lg:mb-5 text-5xl lg:text-base"> To be able to use the Text Gen SD3, you need to download the model and place it in the apporpriate directory. </p>

        <!-- Video Section -->
        <div class="mb-4">
            <h2 class="text-2xl lg:text-xl font-bold mb-4 text-center">Video Tutorial</h2>
            <div class="relative w-full max-w-4xl" style="padding-top: 56.25%;">
                <!-- Replace with your video embed code (YouTube, Vimeo, etc.) -->
                <iframe class="absolute top-0 left-0 w-full h-full" src="https://www.youtube.com/embed/gjsJQgMxbLE?si=HHp1E5tlF-aWrhhb" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>

        <!-- Step 1 -->
        <div class="text-2xl lg:text-xl font-bold mb-4 text-center">Text Instructions</div>
        <div class="flex mb-5 w-full">
            <ol class="flex flex-col list-decimal list-inside text-3xl lg:text-base">
                <li class="text-4xl lg:text-base mb-20 lg:mb-3"> Download
                    <a class="link text-blue-500" href="https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/sd3_medium_incl_clips_t5xxlfp8.safetensors">
                        sd3_medium_incl_clips_t5xxlfp8.safetensors
                    </a>
                </li>
                <li class="text-4xl lg:text-base mb-20 lg:mb-3">Place in ComfyUI_windows_portable_CIW\ComfyUI\models\checkpoints</li>
            </ol>
        </div>
    </div>
</div>
{% endblock %}