app/blueprints/output/routes.py
from flask import render_template, Blueprint, session, request, jsonify
from flask_login import login_required
from app.app import db

from app.models import Generation

output = Blueprint("output", __name__, template_folder='templates', static_folder='static', static_url_path='/output/static')

@output.route('/')
@login_required
def index():
    generations = db.session.query(Generation)\
        .filter_by(user_id=session['_user_id'])\
        .order_by(Generation.created_at.desc())\
        .all()
    return render_template('output/index.html', generations=generations)

# cleanup
# @output.route('/sort_by_newest')
# @login_required
# def sort_by_newest():
#     generations = db.session.query(Generation)\
#     .filter_by(user_id=session['_user_id'])\
#     .order_by(Generation.created_at.desc())\
#     .all()
#     print(session['_user_id'])
#     print(generations)
#     for generation in generations:
#         print(generation.path)
#     return render_template('output/index.html', generations=generations)

# @output.route('/sort_by_oldest')
# @login_required
# def sort_by_oldest():
#     generations = db.session.query(Generation)\
#     .filter_by(user_id=session['_user_id'])\
#     .order_by(Generation.created_at.asc())\
#     .all()
#     print(session['_user_id'])
#     print(generations)
#     for generation in generations:
#         print(generation.path)
#     return render_template('output/index.html', generations=generations)

# @output.route('/filter_by_worflows/<int:blueprint_id>')
# @login_required
# def filter_by_worflows(blueprint_id=None):
#     print("blueprint_id", blueprint_id)
#     generations = db.session.query(Generation)\
#     .filter_by(user_id=session['_user_id'], blueprint_id=blueprint_id)\
#     .order_by(Generation.created_at.desc())\
#     .all()
#     print(session['_user_id'])
#     print(generations)
#     for generation in generations:
#         print(generation.path)
#     return render_template('output/index.html', generations=generations)

@output.route('/filter', methods=['GET'])
@login_required
def filter_generations():
    blueprint = request.args.get('blueprint')
    sort = request.args.get('sort')
    limit = int(request.args.get('limit', 0))  # Convert limit to integer, default to 0 if not provided

    query = db.session.query(Generation).filter_by(user_id=session['_user_id'])

    if blueprint and blueprint != '0':  # Filter by blueprint if specified and not '0'
        try:
            blueprint_id = int(blueprint)
            query = query.filter_by(blueprint_id=blueprint_id)
        except ValueError:
            pass  # Handle if blueprint is not a valid integer

    if sort == 'newest':  # Sort by newest if specified
        query = query.order_by(Generation.created_at.desc())
    elif sort == 'oldest':  # Sort by oldest if specified
        query = query.order_by(Generation.created_at.asc())

    if limit > 0:  # Apply limit if specified and greater than 0
        query = query.limit(limit)

    generations = query.all()

    return render_template('output/index.html', generations=generations)

app/blueprints/output/templates/output/index.html
{% extends "base.html" %}
{% block title %}Output{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="flex flex-col items-center w-full">
        <h1 class="text-8xl lg:text-5xl font-bold mb-20 lg:mb-10 text-center">Output</h1>
        <form action="{{ url_for('output.filter_generations') }}" method="GET" class="w-full lg:w-1/2">
            <div class="collapse collapse-plus bg-base-300 mb-20 lg:mb-5 py-10 lg:py-0 px-10 lg:px-5"> <!-- Adjusted width -->
                <!-- Input element for collapse control -->
                <input type="checkbox" class="peer" />
                <div class="collapse-title text-6xl lg:text-4xl font-bold peer-checked:collapse-open">
                    Filter
                </div>
                <div class="collapse-content flex flex-wrap items-center justify-center lg:justify-start "> <!-- Flexbox for alignment -->
                    <!-- Blueprint Filter Dropdown -->
                    <div class="my-3 lg:my-0 lg:mb-3 lg:mr-3 w-full lg:w-auto">
                        <select id="blueprintFilter" name="blueprint" class="select mb-3 w-full text-4xl lg:text-base lg:w-auto lg:mb-0"> <!-- Added margin -->
                            <option selected disabled>Blueprint</option>
                            <option value="0">All</option>
                            <option value="1">Text Generation</option>
                            <option value="2">Fantasy Character Creator</option>
                            <option value="3">Dress U Up</option>
                        </select>    
                    </div>

                    <!-- Sort By Dropdown -->
                    <div class="mb-3 lg:mr-3 w-full lg:w-auto">
                        <select id="sortByFilter" name="sort" class="select mb-3 w-full text-4xl lg:text-base lg:w-auto lg:mb-0"> <!-- Added margin -->
                            <option selected disabled>Sort By</option>
                            <option value="newest">Newest</option>
                            <option value="oldest">Oldest</option>
                        </select>    
                    </div>
                    
                    <!-- Limit Dropdown -->
                    <div class="mb-3 lg:mr-3 w-full lg:w-auto">
                        <select id="limitFilter" name="limit" class="select mb-3 w-full text-4xl lg:text-base lg:w-auto lg:mb-0"> <!-- Added margin -->
                            <option selected disabled>Limit</option>
                            <option value="0">All</option>
                            <option value="8">8</option>
                            <option value="16">16</option>
                            <option value="40">40</option>
                        </select>
                    </div>
                    <!-- Filter Button -->
                    <button type="submit" class="btn bg-primary btn-primary rounded-lg w-full pb-16 pt-5 text-4xl">Apply Filters</button> <!-- Added margin top and left margin for alignment -->
                </div>
            </div>
        </form>

        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {% set ns = namespace(counter=0) %}
            {% for generation in generations %}
                <div>
                    <img class="h-auto max-w-full rounded-lg" src="{{ generation.path }}" alt="">
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- <script src="{{ url_for('output.static', filename='js/app.js') }}"></script> -->
{% endblock %}