app/blueprints/help/routes.py
from flask import render_template, Blueprint

#import model
from app.models import User

help = Blueprint("help", __name__, template_folder='templates')

@help.route('/')
def index():
    users = User.query.all()
    return render_template('help/index.html')

@help.route('/getting_started')
def getting_started():
    return render_template('help/getting_started.html')

@help.route('/txt_gen')
def txt_gen():
    return render_template('help/txt_gen.html')

@help.route('/fantasy_character_creator')
def fantasy_character_creator():
    return render_template('help/fantasy_character_creator.html')

@help.route('/ip_adapter_headshot')
def ip_adapter_headshot():
    return render_template('help/ip_adapter_headshot.html')

#EDIT12
# Rename to your workflow name and Uncomment the lines below.
# @help.route('/my_new_workflow')
# def my_new_workflow():
#     return render_template('help/my_new_workflow.html')

app/blueprints/home/routes.py
from flask import render_template, Blueprint

#import model
from app.models import User

home = Blueprint("home", __name__, template_folder='templates')

@home.route('/')
def index():
    users = User.query.all()
    return render_template('home/index.html')

app/blueprints/output/routes.py
from flask import render_template, Blueprint, session, request, jsonify
from flask_login import login_required
from app.app import db

from app.models import Generation

output = Blueprint("output", __name__, template_folder='templates', static_folder='static', static_url_path='/output/static')

@output.route('/')
@login_required
def index():
    generations = db.session.query(Generation)\
        .filter_by(user_id=session['_user_id'])\
        .order_by(Generation.created_at.desc())\
        .all()
    return render_template('output/index.html', generations=generations)

# cleanup
# @output.route('/sort_by_newest')
# @login_required
# def sort_by_newest():
#     generations = db.session.query(Generation)\
#     .filter_by(user_id=session['_user_id'])\
#     .order_by(Generation.created_at.desc())\
#     .all()
#     print(session['_user_id'])
#     print(generations)
#     for generation in generations:
#         print(generation.path)
#     return render_template('output/index.html', generations=generations)

# @output.route('/sort_by_oldest')
# @login_required
# def sort_by_oldest():
#     generations = db.session.query(Generation)\
#     .filter_by(user_id=session['_user_id'])\
#     .order_by(Generation.created_at.asc())\
#     .all()
#     print(session['_user_id'])
#     print(generations)
#     for generation in generations:
#         print(generation.path)
#     return render_template('output/index.html', generations=generations)

# @output.route('/filter_by_worflows/<int:blueprint_id>')
# @login_required
# def filter_by_worflows(blueprint_id=None):
#     print("blueprint_id", blueprint_id)
#     generations = db.session.query(Generation)\
#     .filter_by(user_id=session['_user_id'], blueprint_id=blueprint_id)\
#     .order_by(Generation.created_at.desc())\
#     .all()
#     print(session['_user_id'])
#     print(generations)
#     for generation in generations:
#         print(generation.path)
#     return render_template('output/index.html', generations=generations)

@output.route('/filter', methods=['GET'])
@login_required
def filter_generations():
    blueprint = request.args.get('blueprint')
    sort = request.args.get('sort')
    limit = int(request.args.get('limit', 0))  # Convert limit to integer, default to 0 if not provided

    query = db.session.query(Generation).filter_by(user_id=session['_user_id'])

    if blueprint and blueprint != '0':  # Filter by blueprint if specified and not '0'
        try:
            blueprint_id = int(blueprint)
            query = query.filter_by(blueprint_id=blueprint_id)
        except ValueError:
            pass  # Handle if blueprint is not a valid integer

    if sort == 'newest':  # Sort by newest if specified
        query = query.order_by(Generation.created_at.desc())
    elif sort == 'oldest':  # Sort by oldest if specified
        query = query.order_by(Generation.created_at.asc())

    if limit > 0:  # Apply limit if specified and greater than 0
        query = query.limit(limit)

    generations = query.all()

    return render_template('output/index.html', generations=generations)

app/blueprints/profile/routes.py
from flask import redirect, request, render_template, url_for, Blueprint, session, jsonify

from app.helpers import apology
from werkzeug.security import check_password_hash, generate_password_hash

from app.app import db
from app.models import User
from flask_login import login_required
profile = Blueprint("profile", __name__, template_folder='templates')

@profile.route('/')
@login_required
def index():
    return render_template('profile/index.html')

@profile.route('/delete')
def delete():
    # if you want to view the session data.
    # sessionView = jsonify(dict(session))
    # return sessionView

    id = session.get("_user_id")
    user = db.session.query(User).filter(User.id==id).first()
    try:
        db.session.delete(user)
        db.session.commit()
        session.clear()
    except Exception as e:
        print("Error deleting user:", e)

    return render_template('profile/delete.html')

@profile.route("/update", methods=["GET", "POST"])
@login_required
def update():

    user_id = session.get("user_id")
    oldPassword = request.form.get("oldPassword")
    password = request.form.get("password")
    msg = "Password Updated"

    if request.method == "GET":

        return render_template("profile/update.html")

    if request.method == "POST":
        
        user = db.session.query(User).first()

        print(len(user.hash))

        # check old password matches
        if len(user.hash) is None or not check_password_hash(
            user.hash, oldPassword
        ):
            return apology("Old Password does not match", 400)

        # Ensure password was submitted
        elif not password:
            return apology("must provide password", 400)

        # Ensure confirmation password was submitted
        elif not request.form.get("confirmation"):
            return apology("must provide confirmation password", 400)

        # Ensure password match
        elif request.form.get("confirmation") != password:
            return apology("password does not match", 400)

        hash = generate_password_hash(password)

        # Update password
        user.hash = hash
        db.session.commit()

        return render_template("profile/update.html", msg=msg)

app/templates/apology.html
{% extends "base.html" %}

{% block title %}
    Apology
{% endblock %}

{% block content %}
<div class="flex justify-center">    
    <div class="flex flex-col items-center">
        <img alt="{{ top }}" class="border img-fluid w-[800px] lg:w-auto h-auto " src="https://api.memegen.link/images/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?background=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
    </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block meta %} {% endblock %}
        <title>{% block title %}Default{% endblock %}</title>
        <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
        <link rel="manifest" href="/static/img/site.webmanifest">
        <link href="{{url_for('static',filename='css/output.css')}}" rel="stylesheet">
        <link href="{{url_for('static',filename='css/toast.css')}}" rel="stylesheet">
    </head>
    <body>
        <!-- This is a fix for the toast background success color in output.css -->
        <div class="hidden bg-success"></div>
        {% include "nav.html" %}
        <div class="flex flex-col h-screen">
            <div id="toast-container" class="fixed top-0 right-0 m-4 space-y-4 rounded drop-shadow-2xl"></div>
            <div class="flex-1 p-6">
                {% block content %} {% endblock %}
            </div>
            {% include "footer.html" %}
        </div>
        <script src="{{url_for('static',filename='js/toast.js') }}"></script>
        <script src="{{url_for('static',filename='js/utils.js') }}" ></script>
    </body>
</html>

app/templates/footer.html
<footer class="footer footer-center p-4 text-base-content mt-auto"> <!-- Use mt-auto to push footer to bottom -->
  <aside>
      <p>Copyright © 2024 - Jordain Perreault-Joyce</p>
  </aside>
</footer>

app/templates/nav.html
<div class="navbar bg-base-100 z-50">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost h-20 w-20 lg:hidden ">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-20 w-20 transform scale-150" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="0" fill="currentColor" d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" /></svg>
      </div>
      <ul tabindex="0" class="menu text-8xl dropdown-content mt-3 z-50 p-2 shadow bg-base-100 rounded-box w-104 ">
        {% if session["_user_id"] %}
          <li><a class= "mb-5" href="{{ url_for('home.index') }}">Home</a></li>
          <li><a class= "mb-5" href="{{ url_for('output.index') }}">Output</a></li>
          <li><a class= "mb-5" href="{{ url_for('generation.index') }}">Workflows</a></li>
          <li><a class= "mb-5" href="{{ url_for('help.index') }}">Help</a></li>
          <li><a class= "mb-5" href="{{ url_for('profile.index') }}">Profile</a></li>
          <li><a class= "mb-5" href="/auth/logout">Log Out</a></li>
        {% else %}
          <li><a class= "mb-5" href="/auth/register">Register</a></li>
          <li><a class= "mb-5" href="/auth">Log In</a></li>
        {% endif %}
      </ul>
    </div>
    <a class="text-9xl font-serif">CIW</a>
  </div>
  <div class="navbar-end hidden lg:flex lg:justify-center lg:items-center">
    <div class="menu menu-horizontal text-4xl px-1">
      
      {% if session["_user_id"] %}
        <a href="{{ url_for('home.index') }}"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Home</button></a>
        <a href="{{ url_for('output.index') }}"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Output</button></a>
        <a href="{{ url_for('generation.index') }}"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Workflows</button></a>
        <a href="{{ url_for('help.index') }}"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Help</button></a>
        <a href="{{ url_for('profile.index') }}"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Profile</button></a>
        <a href="/auth/logout"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Log Out</button></a>
      {% else %}
        <a href="/auth/register"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Register</button></a>
        <a href="/auth"><button class="btn btn-lg bg-primary btn-primary mx-1 rounded-lg" type="button">Log In</button></a>
      {% endif %}
    </div>
  </div>
</div>